export const CLOUDFRONT_DISTRIBUTION_DOMAIN_NAME =
  process.env.NEXT_PUBLIC_CLOUDFRONT_DISTRIBUTION_DOMAIN_NAME;

if (!CLOUDFRONT_DISTRIBUTION_DOMAIN_NAME) {
  throw new Error(
    "Missing NEXT_PUBLIC_CLOUDFRONT_DISTRIBUTION_DOMAIN_NAME in environment variables"
  );
}
